{{- if .Values.clusterRoleBinding.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRoleBinding.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubectl-api.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
{{- end }}